@echo off
setlocal enabledelayedexpansion

rem ============================================================
rem  find_rscript.bat
rem
rem  Double-click to run. Locates Rscript.exe on this machine
rem  and writes "run_analysis.bat" in this same folder, which
rem  will launch analysis.R via Rscript.
rem
rem  Search order:
rem    1) HKLM\SOFTWARE\R-core\R          (64-bit R)
rem    2) HKLM\SOFTWARE\WOW6432Node\R-core\R  (32-bit R on 64-bit Windows)
rem    3) PATH (via "where")
rem    4) Common install locations under Program Files
rem ============================================================

set "RSCRIPT="

rem --- 1) Registry: 64-bit R ---
for /f "tokens=2,*" %%A in ('reg query "HKLM\SOFTWARE\R-core\R" /v InstallPath 2^>nul ^| find "InstallPath"') do (
    call :TryCandidate "%%B"
)

rem --- 2) Registry: 32-bit R (WOW6432Node) ---
if not defined RSCRIPT (
    for /f "tokens=2,*" %%A in ('reg query "HKLM\SOFTWARE\WOW6432Node\R-core\R" /v InstallPath 2^>nul ^| find "InstallPath"') do (
        call :TryCandidate "%%B"
    )
)

rem --- 3) PATH ---
if not defined RSCRIPT (
    for /f "delims=" %%P in ('where Rscript.exe 2^>nul') do (
        if not defined RSCRIPT set "RSCRIPT=%%P"
    )
)

rem --- 4) Common install folders (glob for any R-x.y.z version folder) ---
if not defined RSCRIPT (
    for %%D in ("%ProgramFiles%\R\R-*" "%ProgramFiles(x86)%\R\R-*") do (
        call :TryCandidate "%%~D"
    )
)

if not defined RSCRIPT (
    echo.
    echo Could not locate Rscript.exe on this system.
    echo Please install R from https://cran.r-project.org/ or, if it is
    echo already installed, run this again after adding its \bin folder
    echo to your PATH.
    echo.
    pause
    exit /b 1
)

rem --- Write the launcher script ---
set "OUTFILE=%~dp0GENERATE_CSV.bat"

(
    echo @echo off
    echo rem Auto-generated by find_rscript.bat
    echo "%RSCRIPT%" "%%~dp0makeCSV.R" %%*
    echo pause
) > "%OUTFILE%"

echo.
echo Found Rscript.exe at:
echo   %RSCRIPT%
echo.
echo Wrote launcher script:
echo   %OUTFILE%
echo.
echo You can now double-click makeCSV.bat to generate an importable .csv from the template .xlsx
echo.
echo It will use find and use all "import....xlsx" files in this folder
pause
exit /b 0

rem ============================================================
rem  :TryCandidate <folder>
rem  Checks a candidate R install folder for Rscript.exe under
rem  \bin\x64, \bin, or the folder itself. Sets RSCRIPT if found.
rem ============================================================
:TryCandidate
set "CAND=%~1"
if not defined CAND exit /b 0
if defined RSCRIPT exit /b 0

if exist "%CAND%\bin\x64\Rscript.exe" (
    set "RSCRIPT=%CAND%\bin\x64\Rscript.exe"
    exit /b 0
)
if exist "%CAND%\bin\Rscript.exe" (
    set "RSCRIPT=%CAND%\bin\Rscript.exe"
    exit /b 0
)
if exist "%CAND%\Rscript.exe" (
    set "RSCRIPT=%CAND%\Rscript.exe"
    exit /b 0
)
exit /b 0
